version: '3.8'

name: vyapaarmitra-production

networks:
  vyapaarmitra:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local
  app_uploads:
    driver: local

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vyapaarmitra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vyapaarmitra}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-vyapaarmitra}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vyapaarmitra-redis
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Auth API
  auth-api:
    build:
      context: ./msmebazaar-v2/apps/auth-api
      dockerfile: Dockerfile
    container_name: vyapaarmitra-auth-api
    restart: unless-stopped
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-vyapaarmitra}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - ENVIRONMENT=production
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=noreply@vyapaarmitra.in
      - SENTRY_DSN=${SENTRY_DSN}
      - PROMETHEUS_ENABLED=true
    volumes:
      - app_logs:/app/logs:rw
    networks:
      - vyapaarmitra
      - backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # MSME API
  msme-api:
    build:
      context: ./msmebazaar-v2/apps/msme-api
      dockerfile: Dockerfile
    container_name: vyapaarmitra-msme-api
    restart: unless-stopped
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-vyapaarmitra}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ENVIRONMENT=production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=vyapaarmitra-uploads
      - AWS_REGION=ap-south-1
      - SENTRY_DSN=${SENTRY_DSN}
      - PROMETHEUS_ENABLED=true
    volumes:
      - app_logs:/app/logs:rw
      - app_uploads:/app/uploads:rw
    networks:
      - vyapaarmitra
      - backend
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'

  # Valuation API
  valuation-api:
    build:
      context: ./msmebazaar-v2/apps/valuation-api
      dockerfile: Dockerfile
    container_name: vyapaarmitra-valuation-api
    restart: unless-stopped
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-vyapaarmitra}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - ENVIRONMENT=production
      - ML_MODEL_PATH=/app/models
      - SENTRY_DSN=${SENTRY_DSN}
      - PROMETHEUS_ENABLED=true
    volumes:
      - app_logs:/app/logs:rw
      - ./ml_models:/app/models:ro
    networks:
      - vyapaarmitra
      - backend
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'

  # Web Frontend
  web:
    build:
      context: ./msmebazaar-v2/apps/web
      dockerfile: Dockerfile
    container_name: vyapaarmitra-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=https://vyapaarmitra.in
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=https://api.vyapaarmitra.in
      - AUTH_API_URL=http://auth-api:8000
      - MSME_API_URL=http://msme-api:8001
      - VALUATION_API_URL=http://valuation-api:8002
    volumes:
      - app_logs:/app/logs:rw
    networks:
      - vyapaarmitra
      - backend
    ports:
      - "3000:3000"
    depends_on:
      auth-api:
        condition: service_healthy
      msme-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Admin Dashboard
  admin-dashboard:
    build:
      context: ./admin-dashboard/backend
      dockerfile: Dockerfile
    container_name: vyapaarmitra-admin
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-vyapaarmitra}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
    volumes:
      - app_logs:/app/logs:rw
    networks:
      - vyapaarmitra
      - backend
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: vyapaarmitra-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/vyapaarmitra.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - app_logs:/var/log/nginx:rw
    networks:
      - vyapaarmitra
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - admin-dashboard
      - auth-api
      - msme-api
      - valuation-api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: vyapaarmitra-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.route-prefix=/'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus-data:/prometheus
    networks:
      - vyapaarmitra
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Background Worker
  worker:
    build:
      context: ./msmebazaar-v2/apps/auth-api
      dockerfile: Dockerfile
    container_name: vyapaarmitra-worker
    restart: unless-stopped
    command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info", "--concurrency=2"]
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-vyapaarmitra}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - ENVIRONMENT=production
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - app_logs:/app/logs:rw
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'