[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"