services:
  # Main Web Application (Frontend + Backend)
  - type: web
    name: msmebazaar-v2
    env: node
    region: oregon
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      # Database Configuration
      - key: DATABASE_URL
        sync: false  # Will be set manually in Render dashboard
      - key: DATABASE_POOL_SIZE
        value: "10"
      - key: DATABASE_MAX_OVERFLOW
        value: "20"
      
      # Application Settings
      - key: NODE_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      
      # Security Keys (to be set manually in Render dashboard)
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      
      # AI Services (to be set manually in Render dashboard)
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-west1-gcp-free
      - key: PINECONE_INDEX_NAME
        value: msmebazaar-vectors
      
      # Payment Integration
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      
      # Email Configuration
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_EMAIL
        value: noreply@vyapaarmitra.in
      
      # Cloud Storage (AWS S3)
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        value: msmebazaar-uploads
      
      # Monitoring & Analytics
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: production
      - key: GA_TRACKING_ID
        sync: false
      
      # Performance Settings
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: "100"
      - key: RATE_LIMIT_BURST_SIZE
        value: "20"
      - key: CACHE_TTL
        value: "3600"
      - key: CACHE_MAX_SIZE
        value: "1000"
      - key: SESSION_TIMEOUT
        value: "86400"
      - key: REFRESH_TOKEN_EXPIRY
        value: "604800"
      
      # Feature Flags
      - key: ENABLE_DEVELOPMENT_TOOLS
        value: "false"
      - key: ENABLE_DEBUG_TOOLBAR
        value: "false"
      - key: ENABLE_SWAGGER_UI
        value: "true"
      - key: METRICS_ENABLED
        value: "true"
      
      # Localization
      - key: DEFAULT_LANGUAGE
        value: en
      - key: SUPPORTED_LANGUAGES
        value: en,hi
      - key: DEFAULT_TIMEZONE
        value: Asia/Kolkata
      
      # CORS Settings
      - key: CORS_ORIGINS
        value: https://vyapaarmitra.in,https://www.vyapaarmitra.in
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      
      # API URLs (will be auto-generated by Render)
      - key: VITE_API_URL
        value: https://msmebazaar-v2.onrender.com/api
      - key: VITE_AUTH_API_URL
        value: https://msmebazaar-v2.onrender.com/auth
      - key: VITE_WS_URL
        value: wss://msmebazaar-v2.onrender.com/ws
    
    # Custom domains
    domains:
      - vyapaarmitra.in
      - www.vyapaarmitra.in
    
    autoDeploy: true
    
    # Health check configuration
    healthCheck:
      path: /health
      timeout: 30
      interval: 30
      retries: 3

  # PostgreSQL Database
  - type: pserv
    name: msmebazaar-postgres
    plan: starter
    region: oregon
    databaseName: msmebazaar_production
    envVars:
      - key: POSTGRES_DB
        value: msmebazaar_production
      - key: POSTGRES_USER
        value: msmebazaar_user
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  # Redis Cache
  - type: redis
    name: msmebazaar-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

databases:
  - name: msmebazaar-postgres
    databaseName: msmebazaar_production
    user: msmebazaar_user