services:
  # ===== DATABASE SERVICES =====

  # PostgreSQL Database
  - type: pserv
    name: msmebazaar-postgres
    plan: starter
    region: singapore
    env: docker
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_DB
        value: msmebazaar_v2
      - key: POSTGRES_USER
        value: msmebazaar
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis Cache & Queue
  - type: redis
    name: msmebazaar-redis
    plan: starter
    region: singapore
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections

  # ===== BACKEND MICROSERVICES =====

  # Auth API Service (Port 8000)
  - type: web
    name: msmebazaar-auth-api
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./backend/auth-api/Dockerfile
    dockerContext: ./backend/auth-api
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/auth-api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmebazaar-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msmebazaar-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # MSME API Service (Port 8001)
  - type: web
    name: msmebazaar-msme-api
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./backend/msme-api/Dockerfile
    dockerContext: ./backend/msme-api
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/msme-api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmebazaar-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msmebazaar-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: S3_BUCKET_NAME
        value: msmebazaar-documents
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # Admin API Service (Port 8002)
  - type: web
    name: msmebazaar-admin-api
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./backend/admin-api/Dockerfile
    dockerContext: ./backend/admin-api
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/admin-api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmebazaar-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msmebazaar-redis
          type: redis
          property: connectionString
      - key: GOOGLE_ANALYTICS_ID
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # Payments API Service (Port 8003)
  - type: web
    name: msmebazaar-payments-api
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./backend/payments-api/Dockerfile
    dockerContext: ./backend/payments-api
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/payments-api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmebazaar-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msmebazaar-redis
          type: redis
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # WhatsApp Bot Service (Port 8004)
  - type: web
    name: msmebazaar-whatsapp-bot
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./backend/whatsapp-bot/Dockerfile
    dockerContext: ./backend/whatsapp-bot
    healthCheckPath: /health
    buildFilter:
      paths:
        - backend/whatsapp-bot/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmebazaar-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msmebazaar-redis
          type: redis
          property: connectionString
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO

  # ===== FRONTEND SERVICE =====

  - type: web
    name: msmebazaar-frontend
    env: node
    plan: starter
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    rootDir: frontend
    healthCheckPath: /
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: VITE_API_BASE_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: VITE_APP_NAME
        value: MSMEBazaar V2
      - key: VITE_APP_VERSION
        value: "2.0.0"
      - key: VITE_APP_URL
        value: https://msmebazaar-frontend.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_GOOGLE_ANALYTICS_ID
        sync: false
      - key: VITE_SENTRY_DSN
        sync: false
      - key: VITE_ENABLE_ANALYTICS
        value: true
      - key: VITE_ENABLE_PWA
        value: true
      - key: VITE_ENABLE_NOTIFICATIONS
        value: true
      - key: VITE_ENABLE_DARK_MODE
        value: true
      - key: NODE_ENV
        value: production
      - key: VITE_BUILD_MODE
        value: production

