services:
  # Frontend - Vite React App
  - type: web
    name: msmebazaar-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port $PORT --host 0.0.0.0
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: VITE_AUTH_API_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: VITE_MSME_API_URL
        value: https://msmebazaar-msme-api.onrender.com
      - key: VITE_ADMIN_API_URL
        value: https://msmebazaar-admin-api.onrender.com
      - key: VITE_PAYMENTS_API_URL
        value: https://msmebazaar-payments-api.onrender.com
    buildFilter:
      paths: ["frontend/**"]
    autoDeploy: true

  # Auth API - OTP Authentication Service
  - type: web
    name: msmebazaar-auth-api
    env: python
    rootDir: backend/auth-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true

  # MSME API - Business Onboarding & Valuation
  - type: web
    name: msmebazaar-msme-api
    env: python
    rootDir: backend/msme-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: AUTH_API_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
    autoDeploy: true

  # Admin API - Dashboard & Management
  - type: web
    name: msmebazaar-admin-api
    env: python
    rootDir: backend/admin-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: AUTH_API_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: MSME_API_URL
        value: https://msmebazaar-msme-api.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true

  # Payments API - Razorpay/Stripe Gateway
  - type: web
    name: msmebazaar-payments-api
    env: python
    rootDir: backend/payments-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: AUTH_API_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true

  # WhatsApp Bot API - Bot Connector
  - type: web
    name: msmebazaar-whatsapp-bot
    env: python
    rootDir: backend/whatsapp-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: AUTH_API_URL
        value: https://msmebazaar-auth-api.onrender.com
      - key: MSME_API_URL
        value: https://msmebazaar-msme-api.onrender.com
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: WEBHOOK_URL
        value: https://msmebazaar-whatsapp-bot.onrender.com
      - key: REDIS_URL
        sync: false
    autoDeploy: true