apiVersion: v1
kind: ConfigMap
metadata:
  name: msme-config
  namespace: msme-platform
data:
  NODE_ENV: "production"
  TYPESENSE_HOST: "typesense-service"
  TYPESENSE_PORT: "8108"
  TYPESENSE_API_KEY: "xyz"
  REDIS_URL: "redis://redis-service:6379"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"