apiVersion: v1
kind: Secret
metadata:
  name: msme-square-secrets
  namespace: msme-square
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL21zbWVfc3F1YXJl
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==
  RAZORPAY_KEY_ID: cnpwX3Rlc3RfMTIzNDU2Nzg5MA==
  RAZORPAY_KEY_SECRET: eW91ci1yYXpvcnBheS1zZWNyZXQ=
  WHATSAPP_ACCESS_TOKEN: eW91ci13aGF0c2FwcC10b2tlbg==
  WHATSAPP_PHONE_NUMBER_ID: eW91ci1waG9uZS1udW1iZXItaWQ=
  OPENAI_API_KEY: c2stcHJvai0xMjM0NTY3ODkw
  STRIPE_SECRET_KEY: c2tfdGVzdF8xMjM0NTY3ODkw
  REDIS_PASSWORD: eW91ci1yZWRpcy1wYXNzd29yZA==
  POSTGRES_PASSWORD: eW91ci1wb3N0Z3Jlcy1wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: msme-square
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5leGFtcGxlLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogInVzZXJuYW1lIiwKICAgICAgInBhc3N3b3JkIjogInBhc3N3b3JkIiwKICAgICAgImVtYWlsIjogImVtYWlsQGV4YW1wbGUuY29tIiwKICAgICAgImF1dGgiOiAiZFhObGNtNWhiV1U2Y0dGemMzZHZjbVE9IgogICAgfQogIH0KfQ==