version: "3.9"
services:
  notification-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - kafka

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
