# Railway Deployment Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: railway-config
data:
  PORT: "5000"
  NODE_ENV: "production"
  RAILWAY_STATIC_URL: "https://your-app.railway.app"
  
---
# Railway Production Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msme-railway-app
  labels:
    app: msme-railway-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msme-railway-app
  template:
    metadata:
      labels:
        app: msme-railway-app
    spec:
      containers:
      - name: app
        image: ghcr.io/your-org/msme-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: JWT_SECRET
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: RAZORPAY_KEY_SECRET
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: SENTRY_DSN
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: REDIS_URL
        - name: TYPESENSE_HOST
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: TYPESENSE_HOST
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: railway-secrets
              key: TYPESENSE_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: msme-railway-service
spec:
  selector:
    app: msme-railway-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer