services:
  - type: web
    name: msme-square-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: msme-square-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    
  - type: redis
    name: msme-square-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: msme-square-db
    databaseName: msme_square
    user: msme_user
    plan: starter