databases:
  - name: msme-postgres
    databaseName: msme_square
    user: postgres
    plan: starter
    postgresMajorVersion: 15

  - name: msme-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

services:
  - type: web
    name: msme-square-api
    runtime: node
    plan: starter
    buildCommand: npm install --workspaces && npm run build --workspace=@msmebazaar/api
    startCommand: npm start --workspace=@msmebazaar/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: msme-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: msme-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: MSG91_AUTH_KEY
        sync: false
    healthCheckPath: /health
    domains:
      - msme-square-api.onrender.com

  - type: web
    name: msme-square-frontend
    runtime: node # ⬅️ was static, changed to node
    plan: starter
    buildCommand: npm install --workspaces && npm run build --workspace=@msmebazaar/web
    startCommand: npm start --workspace=@msmebazaar/web
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://msme-square-api.onrender.com
      - key: NEXT_PUBLIC_APP_URL
        value: https://msme-square.onrender.com
      - key: VITE_API_URL
        value: https://msme-square-api.onrender.com
    domains:
      - msme-square.onrender.com
    healthCheckPath: /

  - type: worker
    name: msme-square-scheduler
    runtime: node
    buildCommand: npm install --workspaces
    startCommand: npm run scheduler --workspace=@msmebazaar/scheduler
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: msme-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: msme-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
