apiVersion: v1
kind: Namespace
metadata:
  name: msmebazaar-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: msmebazaar-staging
  labels:
    app: recommendation-service
    version: v1
    environment: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
        version: v1
    spec:
      containers:
      - name: recommendation-service
        image: ${RECOMMENDATION_SERVICE_IMAGE}
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: POSTGRES_HOST
          value: "postgres-main"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "msmebazaar"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_HOST
          value: "redis-main"
        - name: REDIS_PORT
          value: "6379"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server:5000"
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/recommendation_stats
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/recommendation_stats
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: msmebazaar-staging
  labels:
    app: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
  - port: 8004
    targetPort: 8004
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendation-service-ingress
  namespace: msmebazaar-staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - staging-api.msmebazaar.com
    secretName: staging-api-tls
  rules:
  - host: staging-api.msmebazaar.com
    http:
      paths:
      - path: /api/recommendations
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 8004
      - path: /api/feedback
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 8004
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  namespace: msmebazaar-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: msmebazaar-staging
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # base64 encoded password
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendation-service-hpa
  namespace: msmebazaar-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendation-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80