# Kubernetes deployment configuration for microservices
apiVersion: v1
kind: Namespace
metadata:
  name: msme-atlas
---
# API Gateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: msme-atlas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: msme-atlas/api-gateway:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: GATEWAY_PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: msme-atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: msme-atlas/auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: SERVICE_NAME
          value: "auth"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# MSME Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msme-service
  namespace: msme-atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msme-service
  template:
    metadata:
      labels:
        app: msme-service
    spec:
      containers:
      - name: msme-service
        image: msme-atlas/msme-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: SERVICE_NAME
          value: "msme"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Valuation Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valuation-service
  namespace: msme-atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: valuation-service
  template:
    metadata:
      labels:
        app: valuation-service
    spec:
      containers:
      - name: valuation-service
        image: msme-atlas/valuation-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: SERVICE_NAME
          value: "valuation"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: msme-atlas
spec:
  selector:
    app: api-gateway
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: msme-atlas
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: msme-service
  namespace: msme-atlas
spec:
  selector:
    app: msme-service
  ports:
  - port: 3002
    targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: valuation-service
  namespace: msme-atlas
spec:
  selector:
    app: valuation-service
  ports:
  - port: 3003
    targetPort: 3003