global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Monitoring Service
  - job_name: 'ml-monitoring'
    static_configs:
      - targets: ['ml-monitoring:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Model Performance Metrics
  - job_name: 'model-metrics'
    static_configs:
      - targets: ['ml-monitoring:8005']
    metrics_path: '/metrics'
    scrape_interval: 60s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'model_.*'
        target_label: 'service'
        replacement: 'ml-models'

  # Celery Workers
  - job_name: 'celery-workers'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/api/workers'
    scrape_interval: 30s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # MLflow Server
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow-server:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Airflow
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: '/admin/metrics'
    scrape_interval: 60s

  # Application Services
  - job_name: 'valuation-service'
    static_configs:
      - targets: ['valuation-service:8001']
    metrics_path: '/metrics'

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8004']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8003']
    metrics_path: '/metrics'

  - job_name: 'admin-dashboard'
    static_configs:
      - targets: ['admin-dashboard:4000']
    metrics_path: '/api/admin/system/health'

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'

  # Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'