apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-monitoring-service
  namespace: msmebazaar-prod
  labels:
    app: ml-monitoring-service
    version: v1
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ml-monitoring-service
  template:
    metadata:
      labels:
        app: ml-monitoring-service
        version: v1
    spec:
      containers:
      - name: ml-monitoring-service
        image: ${ML_MONITORING_SERVICE_IMAGE}
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: POSTGRES_HOST
          value: "postgres-main"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "msmebazaar"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_HOST
          value: "redis-main"
        - name: REDIS_PORT
          value: "6379"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server:5000"
        - name: ENVIRONMENT
          value: "production"
        - name: CELERY_BROKER_URL
          value: "redis://redis-main:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-main:6379/0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/models/status
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/models/status
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ml-monitoring-service
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: ml-monitoring-service
  namespace: msmebazaar-prod
  labels:
    app: ml-monitoring-service
spec:
  selector:
    app: ml-monitoring-service
  ports:
  - port: 8005
    targetPort: 8005
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-monitoring-service-ingress
  namespace: msmebazaar-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "50"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.msmebazaar.com
    secretName: prod-api-tls
  rules:
  - host: api.msmebazaar.com
    http:
      paths:
      - path: /api/models
        pathType: Prefix
        backend:
          service:
            name: ml-monitoring-service
            port:
              number: 8005
      - path: /api/retrain
        pathType: Prefix
        backend:
          service:
            name: ml-monitoring-service
            port:
              number: 8005
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-monitoring-service-hpa
  namespace: msmebazaar-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-monitoring-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ml-monitoring-service-pdb
  namespace: msmebazaar-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ml-monitoring-service