
name: Retrain Model

on:
  schedule:
    - cron: '0 2 * * SUN'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Retrain
        run: python apps/ml-api/train_model.py
