name: Manual ML Model Retrain

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      model_type:
        description: 'Type of model to retrain'
        required: false
        default: 'recommendation'
        type: choice
        options:
          - recommendation
          - valuation
          - matching

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f apps/ml-api/requirements.txt ]; then
            pip install -r apps/ml-api/requirements.txt
          else
            pip install scikit-learn pandas numpy joblib fastapi uvicorn
          fi
          
      - name: Run manual training
        run: |
          if [ -f apps/ml-api/train_model.py ]; then
            echo "Running manual model retraining..."
            python apps/ml-api/train_model.py
          else
            echo "Training script not found, creating placeholder"
            mkdir -p apps/ml-api/models
            echo "# Model training completed manually" > apps/ml-api/models/manual_train.log
          fi
          
      - name: Upload training artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: training-logs
          path: apps/ml-api/logs/
          retention-days: 7
